docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: v1/intro.md
site_name: 'api-tools-{component}'
site_description: ''
repo_url: 'https://github.com/laminas-api-tools/api-tools-{component}'
